//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHome.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int BuyerId { get; set; }
        public string PaymentType { get; set; }
        public string IsCompleted { get; set; }
        public int ProjectId { get; set; }
        public int Price { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
